[package]
name = "waifu2x"
version = "0.1.0"
authors = ["DarkSky"]
edition = "2018"
description = "A waifu2x-ncnn-vulkan Rust binding"
license = "AGPL-3.0-or-later"
homepage = "https://github.com/darkskygit/waifu2x.rs"
repository = "https://github.com/darkskygit/waifu2x.rs"
keywords = ["binding", "waifu2x", "ncnn", "vulkan"]
include = ["src/**/*", "waifu2x/**/*", "build.rs", "LICENSE", "README.md"]
readme = "README.md"

[features]
default = []
noise = []
upconv7 = []

[dependencies]
libc = "0.2.97"
ncnn-sys = "0.1.4"

[dependencies.image]
version = "0.23.14"
default-features = false

[build-dependencies]
cmake = "0.1.45"
