[package]
name = "waifu2x-rs"
version = "0.1.0"
authors = ["DarkSky"]
edition = "2018"

[dependencies]
libc = "0.2.60"
image = "0.22.1"

[build-dependencies]
cmake = "0.1.40"
path-absolutize = "1.1.6"